### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by jose2007kj** [tiagohs/stuffs-admin#2]
hi 
Thanks for this opensource repo,
Can you share some learning material links you used,

thanks

**Comment by tiagohs** [comment]
Hi!

Some courses:

https://www.pluralsight.com/courses/spring-boot-first-application
https://www.pluralsight.com/paths/core-spring

But the documentation from the JFoenix, Spring Boot and JavaFx helped me a lot on this project.
All links are in the Readme.

Abs!

**Comment by jose2007kj** [comment]
Thanks a lot @tiagohs wish you all the success
