### ISSUE TITLE
pagination doesn't work

### ISSUE THREAD

**Issue by breakyang** [tiagohs/stuffs-admin#3]
It  could be a bug for pagination.

TableUitls.java Line 73, 
        pagination.setCurrentPageIndex(0);
should be         
        pagination.setCurrentPageIndex(pageIndex);

![image](https://user-images.githubusercontent.com/3748787/65826718-5a67ec80-e2bc-11e9-9cdd-7d53f637e6ea.png)

**Comment by tiagohs** [comment]
Done and commited in master!

Thanks @breakyang !
